name: flutter_chatbot_app
description: A simple chatbot app using OpenAI's GPT model.
publish_to: 'none' # Remove this line if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  

dependencies:
  google_place: any
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7 # Updated version
  percent_indicator: ^4.2.2
  flutter:
    sdk: flutter
  http: ^0.13.0
  cupertino_icons: ^1.0.6
  video_player: ^2.7.0
  google_fonts: ^4.0.4
  file_picker: ^10.1.7
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  image_picker: ^1.0.4
  speech_to_text: ^7.0.0
  flutter_tts: ^3.6.3
  url_launcher: ^6.2.5
  intl: ^0.19.0
  fl_chart: ^0.64.0 # Or the latest version from pub.dev
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/banner.jpg
    - assets/picture_0.jpg
    - assets/picture_1.jpg
    - assets/picture_2.jpg
    - assets/picture_3.jpg
    - assets/picture_4.jpg
    - assets/picture_5.jpg
    - assets/logo.png
    - assets/picture_ricebag.jpg
    - assets/picture_apple.jpg
    - assets/picture_banana.jpg
    - assets/picture_bread.jpg
    - assets/picture_vege.jpg
    - assets/picture_tomato.jpg
    - assets/cina.jpeg
    - assets/farm.png
    - assets/mas.jpeg
    - assets/izal.jpeg
    - assets/el.jpeg
    - assets/sab.jpeg
    - assets/fahmi.jpeg
    - assets/haz.jpeg
    - assets/hanim.jpeg




 
